### ISSUE TITLE
[bug bash] typo in 57.teams-conversation-bot/README.md

### ISSUE THREAD

**Issue by Andrea-Orimoto** [microsoft/BotBuilder-Samples#1931]
## Describe the bug
https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/57.teams-conversation-bot/README.md#interacting-with-the-bot
![image](https://user-images.githubusercontent.com/17152540/68248893-920c3780-ffd2-11e9-8d99-6f0c05fa3828.png)

[bug]

**Comment by anusharavindrar** [comment]
Also includes the typo 'memeber' and 'converstation's' in the Result step.
![57](https://user-images.githubusercontent.com/48731427/68253279-64c48700-ffdc-11e9-8d83-c4935b3e9438.png)

**Comment by johnataylor** [comment]
fixed

**Comment by anusharavindrar** [comment]
The typos 'memebers' and 'converstation's' in the 3. MessageAllMembers section Result step are not fixed yet.

**Comment by anusharavindrar** [comment]
@johnataylor The typos 'memebers' and 'converstation's' in the 3. MessageAllMembers section Result step are not fixed yet(both in the C# and JS samples README.md files)

**Comment by EricDahlvang** [comment]
Thanks @anusharavindrar ... these are fixed now.
