### ISSUE TITLE
50.teams-messaging-extensions-search cannot work on channel

### ISSUE THREAD

**Issue by brightInGit** [microsoft/BotBuilder-Samples#2879]
This NodeJS sample  cannot work on the Teams->General channel. It simply failed in channel if I directly click the New Conversation to use this extension. It returns back without any result after selecting one item in the list. Being strange, It can work if I typed in any text in the message input box and then click the New Conversation to use this extension.  It works well on Chat also.  If I run this on Teams' web version, i got the same issue. I can see the console is having the error message: TextEditor: Cannot read property 'scrollIntoView' of undefined. Another error message is:  Cannot read property 'isChannelConversation' of undefined. 
Here is the link of the sample: https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/50.teams-messaging-extensions-search

**Comment by brightInGit** [comment]
I found the similar issue and the discussion on the stackoverflow: https://stackoverflow.com/questions/62516251/microsoft-teams-bot-messaging-extension-invoke-selectitem-not-working-as-expect.  One answer is saying there is a known bug for the "Reply".  The comment for the answer said the "New conversation" has the same issue now. I kind of is encountering the same issue.

**Comment by brightInGit** [comment]
I run some other published message extensions. They work well. Does that mean they are coded in .Net? Only NodeJS version cannot work?

**Comment by mdrichardson** [comment]
As noted in the StackOverflow issue you linked, this is currently a bug in Teams. I'll reach out to them for an update.

However, it does work as described in [the README](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/50.teams-messaging-extensions-search#interacting-with-the-bot-in-teams) via the command box:

![image](https://user-images.githubusercontent.com/40401643/97610069-a7435880-19d1-11eb-8d17-8ea5ae8fd9db.png)

> I run some other published message extensions. They work well. Does that mean they are coded in .Net? Only NodeJS version cannot work?

I just tested this in both Node and .NET and experienced the same thing. Since it works via the Command Bar and the bot responds appropriately, I'm relatively certain this is a Teams issue.

**Comment by brightInGit** [comment]
@mdrichardson Thank you for the quick response. Do you think this can be fixed in the next release of Teams?

**Comment by mdrichardson** [comment]
@brightInGit I'm not on the Teams team, so I can't say. But I'll post an update here when I hear back from them.

**Comment by clearab** [comment]
I don't believe the StackOverflow question linked to above is the root of the problem you're experiencing. That issue is specific to the `onMessagingExtensionSelectItem` event not firing as expected. Is your bot using that event, or are you returning the entire card + preview in response to the initial query?

Is this only failing in the General channel, and works in other channels? (I haven't been able to reproduce this locally)

**Comment by mdrichardson** [comment]
@brightInGit Just as an update, Teams is looking into this, now.

**Comment by mrivera-ms** [comment]
@clearab assigning this to you as @mdrichardson is not available. Could you please update with status?

**Comment by clearab** [comment]
The Teams group is reporting that this bug has been fixed, and is rolling through their deployment rings. The expectation is that it will be globally available by January.

**Comment by clearab** [comment]
The fix for this should be rolling out globally now. Please re-open if you continue to experience issues.

**Comment by mattlavallee** [comment]
@clearab - has this actually been fixed? Using Teams build version 1.4.00.2879 this still appears to be an issue

**Comment by clearab** [comment]
@mattlavallee - Thanks for bringing this to my attention, I'm confirming with the product team on the status.

**Comment by mattlavallee** [comment]
Hi @clearab - have you heard back from the product team regarding this issue?

**Comment by mattlavallee** [comment]
@clearab - Just wanted to provide you with a bit more information here. I am currently on Microsoft Teams v1.4.00.3484 (64-bit)

I am using some test code that is almost identical to [Sample 50](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/javascript_nodejs/50.teams-messaging-extensions-search/bots/teamsMessagingExtensionsSearchBot.js)

```ts
const attachments = [];
const heroCard = CardFactory.heroCard("Image Test");
const previewCard = CardFactory.heroCard("Thumbnail");
previewCard.content.tap = {
  type: "invoke",
  value: {
    description: "Tap test",
  },
};
attachments.push({
  ...heroCard,
  preview: previewCard,
});

return {
  composeExtension: {
    type: "result",
    attachmentLayout: "list",
    attachments,
  }
};
```

I've set up breakpoints in many locations to see if this message was getting lost somewhere along the way such as in:
  * My Bot's `handleTeamsMessagingExtensionSelectItem` handler
  * Server in the `express.post("/api/messages", ...` handler
  * Inside of `adapter.processActivity` within the `/api/messages` handler
  * In `teamsActivityHandler.js` at the top of the following methods (I know some don't make sense, but I'm grasping at anything here):
    * `onInvokeActivity` 
    * `handleTeamsCardActionInvoke`
    * `handleTeamsMessagingExtensionCardButtonClicked`
    * `handleTeamsTaskModuleFetch`
    * `handleTeamsTaskModuleSubmit`
    * `handleTeamsAppBasedLinkQuery`
    * `handleTeamsMessagingExtensionQuery`
    * `handleTeamsMessagingExtensionSelectItem`
    * `handleTeamsMessagingExtensionSubmitActionDispatch`
    * `handleTeamsMessagingExtensionSubmitAction`
    * `handleTeamsMessagingExtensionFetchTask`
  * In `activityHandler.js` at the top of the following methods
    * `onTurn`
    * `onMessage`
    * `onEvent`
    * `onUnrecognizedActivityType`
    * `run`
    * `onTurnActivity`
    * `onMessageActivity`
    * `onInvokeActivity`
    * `onEventActivity`
    * `on`
    * `handle`

I receive a message when I first type, entering `handleTeamsMessagingExtensionQuery`. Once I click a result which should invoke the `tap` action I get nothing. None of the above breakpoints are ever hit; it seems as if the message/action never makes it out of Teams and back to the server

**Comment by clearab** [comment]
Hi - I've spoken with the product team and they believed the fix had been implemented and published. I'll try and get a repro this evening so I can continue pushing.

**Comment by clearab** [comment]
I was able to use this sample and get the selectItem event to fire on both the Windows desktop client and the web browser client. I've tried from 1:1 chats, group chats, and both the "reply" and "New Conversation" options in a channel.

If you check your ngrok logs, you should be able to see the event
![image](https://user-images.githubusercontent.com/1139814/108146758-9acb3480-7082-11eb-8dfc-52f5ccc162a5.png)

What client & context are you triggering from (i.e. browser client & "new conversation" button in a channel)? Are you able to receive the invoke from any client/context at all? Is there anything unique about your environment at all?

**Comment by mattlavallee** [comment]
@clearab - thank you for taking the time to investigate this with me. I was able to run two more scenarios on my corporate environment and am able to narrow the issue down to something in our environment.
I was able to run this sample and can confirm that I see it working. We can close this issue out again

**Comment by clearab** [comment]
Awesome, glad it is working!

**Comment by mattlavallee** [comment]
Hi @clearab 

I hate to reopen this issue, but has this potentially been broken in Microsoft Teams again? the selectItem handler was working at the end of May.
On June 3 I received a teams update: `1.4.00.14673 (64-bit)` and now when debugging I am seeing that the `handleTeamsMessagingExtensionSelectItem` is never getting hit

**Comment by clearab** [comment]
@Wajeed-msft - can someone on your team take a look at this one?

**Comment by Chetana-MSFT** [comment]
Hi @brightInGit We are looking into this issue, Will get back soon.

**Comment by Chetana-MSFT** [comment]
Hi @mattlavallee Could please explain briefly where exactly you are facing the issue.

**Comment by mattlavallee** [comment]
@Chetana-MSFT - as mentioned [above](https://github.com/microsoft/BotBuilder-Samples/issues/2879#issuecomment-857802850) in Microsoft Teams.
Our search extension bot returns a result from `handleTeamsMessagingExtensionQuery` similar to the sample code [here](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/javascript_nodejs/50.teams-messaging-extensions-search/bots/teamsMessagingExtensionsSearchBot.js#L34-L40).

The result has the tap action defined however upon tapping the `handleTeamsMessagingExtensionSelectItem` is never hit

**Comment by Chetana-MSFT** [comment]
@mattlavallee I have reproduced the same [code](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/javascript_nodejs/50.teams-messaging-extensions-search/bots/teamsMessagingExtensionsSearchBot.js#L34-L40) that you have provided. It is working completely fine at our end and so, I suggest you to retry once again at your end.

**Comment by mattlavallee** [comment]
@Chetana-MSFT -

I have drastically simplified our code to look more or less like the following:

**handleTeamsMessagingExtensionQuery**
```ts
public async handleTeamsMessagingExtensionQuery(context: TurnContext, query: MessagingExtensionQuery): Promise<MessagingExtensionResponse> {
  const heroCard = CardFactory.heroCard('TEST');
  const preview = CardFactory.heroCard('PREVIEW');
  preview.content.tap = {
    type: 'invoke',
    value: {
      description: 'testing',
    },
  };
  const attachment = {...heroCard, preview};

  return {
    composeExtension: {
      type: 'result',
      attachmentLayout: 'list',
      attachments: [attachment],
    },
  } as MessagingExtensionResponse;
}
```

**Bot Entry**

```ts
app.post('/api/messages', async (req: any, res: any) => {
  adapter.processActivity(req, res, async context => {
    console.log('CONTEXT: ' + JSON.stringify(context));
    await bot.run(context);
  });
});
```

In the `/api/messages` handler I would expect to see two hits, one for `composeExtension/query` and a second when I tap a result for `composeExtension/selectItem`. However, with this simple example I get a single hit for `composeExtension/query` and it appears as if Microsoft Teams is not sending any event to this API for `composeExtension/selectItem`

I mentioned above that I am on Teams build `1.4.00.14673 (64-bit)`. For what it's worth, my company is part of the TAP program, so if that build number plus TAP leads to a different version of Teams, perhaps the issue is currently only in the TAP release?

**Comment by Chetana-MSFT** [comment]
@mattlavallee Could you please go through the syntax of `handleTeamMessagingExtension`  as provided in the [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?tabs=typescript). 
![image](https://user-images.githubusercontent.com/84448379/123075690-188abc80-d436-11eb-82b6-f0242b2cb189.png)

**Comment by mattlavallee** [comment]
@Chetana-MSFT - I'm not really sure what you're getting at there. Yes I have gone through the documentation and my previous code sample lines up not only with that documentation but also with the BotBuilder-Samples example code that has been referenced several times in this issue.

Have you checked that TAP build version of Microsoft Teams that I have specified?
I suspect that since the API message endpoint for the bot is not receiving a response at all that the issue is in Teams not sending that request

**Comment by mattlavallee** [comment]
@Chetana-MSFT / @clearab 

This is also affecting Microsoft Teams version `TAP 1.4.00.16575 (64-bit)` which my company received as an update on 6/21/2021

**Comment by clearab** [comment]
@Chetana-MSFT please attempt to repro across the various rings, I believe the TAP ring is like 3.0.

**Comment by Wajeed-msft** [comment]
@mattlavallee - I tried this in different rings, we are not able to repro the issue at our end. Could you please share the Bot Id and timestamp so that we can check logs?

**Comment by mattlavallee** [comment]
Hi @Wajeed-msft 

The Bot Id is `a888a38f-1225-4d24-b2e4-8c0093179a92`

I ran through two test cases between 13:17:00 - 13:18:59 EDT (this equates to 17:17:00 - 17:18:59 UTC)

**Comment by Wajeed-msft** [comment]
@mattlavallee - I could not find anything specific to debug this further in logs around the timeframe mentioned. Could you please try this [manifest.zip](https://github.com/microsoft/BotBuilder-Samples/files/6765509/manifest.zip) and let me know if you see same issue? When you select any item I have appended OnTeamsMessagingExtensionSelectItemAsync in description from the same even.
![image](https://user-images.githubusercontent.com/31851992/124500559-9d35ed00-dddd-11eb-8354-fc353cdeb6b3.png)

@clearab - could you please also give it a try see if it reproes for you?

**Comment by clearab** [comment]
Works fine for me, testing in R1 on Windows

**Comment by mattlavallee** [comment]
I am on vacation currently but I will be back in the office to test probably July 14 but it may get pushed to July 15. Thanks for your patience

**Comment by mattlavallee** [comment]
@clearab / @Wajeed-msft  - given the handler mentioned in https://github.com/microsoft/BotBuilder-Samples/issues/2879#issuecomment-874231506 it seems the test app was written in C#. Is it possible that the C# BotBuilder and NodeJS Botbuilder differ somehow?

The sample manifest works for me however an equivalent simple NodeJS example does not

**Comment by Wajeed-msft** [comment]
Thanks for confirming that issue is not with the Teams platform. Let me try NodeJS sample from my side to see if things differ.

**Comment by mattlavallee** [comment]
@Wajeed-msft - have you had any luck checking the NodeJS sample?

**Comment by Wajeed-msft** [comment]
@mattlavallee - Tried Node sample as well. Worked fine for me. I'll deploy the sample and share the manifest with you.

**Comment by mattlavallee** [comment]
@Wajeed-msft / @clearab - It looks like in the TAP release from July 16, 2021, version `1.4.00.19572 (64 bit)` the issue is resolved.

My simple NodeJS test bot (exact same code from 28 days ago [here](https://github.com/microsoft/BotBuilder-Samples/issues/2879#issuecomment-870778164)) now works as expected
