### ISSUE TITLE
Load, Build and Runtime Error on Adaptive Dialog dotnetcore c# sample

### ISSUE THREAD

**Issue by philip-mc** [microsoft/BotBuilder-Samples#2941]
## Sample information
1. Sample type: \samples\
2. Sample language: dotnetcore c#
3. Sample name: /adaptive-dialog/09.integrating-composer-dialogs

## Describe the bug
If I run the sln file for the adaptive dialog folder the only project that fails to load in visual studio 2019 is number 9 (the only 1 I actually need!)

![image](https://user-images.githubusercontent.com/73343537/99631558-b39c5d80-2a33-11eb-82f2-9b436aa4a132.png)

Yesterday I was getting this error but I cannot reproduce it this morning for some reason....

![image](https://user-images.githubusercontent.com/73343537/99632344-f6ab0080-2a34-11eb-833e-66f2e1220464.png)

If I load a local folder in VS the folder structure loads fine and then if I try to run the csproj file I get the message "please select a valid startup file". 

Folowing this I try to run in cmd line using dotnet run and the bot loads and I can test locally.  

Unsure how to get the sample bot to build and run in VS. I prefer VS over cmd line for testing and publishing.

## To Reproduce
As above

## Expected behavior
Be able to use the sln. file for this project and be able to build the bot, test locally and publish in and from VS to Azure.

**Comment by johnataylor** [comment]
If you would like to create a Dialog in code you should follow the samples in the samples folder here https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore . At this time Adaptive-Dialogs are not a recommended code-first development story. They are, however, significant because they are an important part of the underlying runtime engine when you create a bot with the Composer.

We will be removing these samples so they do not cause further confusion. We plan to provide a single Adaptive Dialog sample that illustrates, for the curious, how the runtime actually works behind the scenes. Though this is not the prescribed way to factor business logic, there are other scenarios for code-first Adaptive Dialogs, for example, if you were extending the behavior you might subclass, and provide some coded unit tests where you constructed the execution tree inline in code.

**Comment by johnataylor** [comment]
In the meantime, while we work on cleaning up the story here.

I found I can get this to build in VS by first doing a "clean solution" and then a "rebuild solution."

**Comment by EricDahlvang** [comment]
@philip-mc thank you for raising this issue.  We've merged a fix into the main branch which addresses the build/rebuild bug.

As John mentioned, we will be re-organizing these samples soon.  We appreciate your feedback.

**Comment by philip-mc** [comment]
Hey,

thanks for the input guys. I have re downloaded the code and managed to run the bot locally so thanks for this. I still get a couple of errors tho see attached screenshot. 

![image](https://user-images.githubusercontent.com/73343537/100593063-d827ed80-32ef-11eb-80e5-737b026049a9.png)


@johnataylor I don't follow what you are saying can you please re phrase. I am using adaptive dialogs as part of a wider project and using the sample code as a guide in some cases.

**Comment by Zerryth** [comment]
@philip-mc To clarify what John was saying, he means that you could do as how you are doing and use Adaptive Dialogs in a code-first fashion, however it's not the recommended way to use Adaptive Dialogs. Instead, it is currently recommended that you use the Bot Framework Composer, if you are using Adaptive Dialogs. See Composer docs [here](https://docs.microsoft.com/en-us/composer/introduction).

As for the ngrok error, you'd need to follow the instructions given in the error to see what the Emulator is complaining about in the logs, since we can't see the ngrok tab in your given screenshot.
